"""Create exercise variations model

Revision ID: e39af83d1f1e
Revises: 2e117fb38126
Create Date: 2025-03-29 07:16:22.495032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39af83d1f1e'
down_revision = '2e117fb38126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('variation_type', sa.String(length=50), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_variations_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_exercise_variations_routine_id_routines')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('routine_exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('routine_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_routine_exercises_exercise_id_exercises'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name='fk_routine_exercises_routine_id_routines'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_variations')
    # ### end Alembic commands ###
