"""updated backend

Revision ID: e7a37ec37cfa
Revises: ac2504861ca6
Create Date: 2025-03-30 21:03:57.349682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a37ec37cfa'
down_revision = 'ac2504861ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_variations_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_variations_routine_id_routines')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercise_variations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_variations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('variation_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('routine_id', sa.INTEGER(), nullable=True),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='fk_exercise_variations_exercise_id_exercises'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name='fk_exercise_variations_routine_id_routines'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('variations')
    # ### end Alembic commands ###
